phrase:
  access_token: 6f26176255be72b61684b3ef6763dfe466f0735078c593625b6745264486b269
  project_id: 98a7a0af5c79bb1efbf53e797de8097e
  file_format: simple_json
  
  push:
    sources:
    - file: de-DE.json
      params:
        file_format: simple_json
        locale_id: de-DE
        
    - file: en-GB.json
      params:
        file_format: simple_json
        locale_id: en-GB

  pull:
    targets:
    - file: de-DE.json
      params:
        file_format: simple_json
        locale_id: de-DE
        
    - file: en-GB.json
      params:
        file_format: simple_json
        locale_id: en-GB
